### ISSUE TITLE
Interpreter Usage Example Outdated?

### ISSUE THREAD

**Issue by bpops** [Dih5/xpecgen#18]
I believe the screenshot of the interpreter usage example (img/DemoConsole.png) is out of date. Following it throws the following error:
`module 'xpecgen' has no attribute 'calculate_spectrum'`
I believe this is the correct way to load it in:
`from xpecgen import xpecgen as xg`

I would fix it myself and submit a PR but on a mac and the UI would contrast with your GUI example screenshot.

**Comment by Dih5** [comment]
Thank you for noticing and my apologies for the late reply, I completely forgot about this.

I will upload updated images now.
