### ISSUE TITLE
Package is not actually packaged

### ISSUE THREAD

**Issue by jkahn** [Dih5/xpecgen#2]
Here from [the JOSS review thread:](https://github.com/openjournals/joss-reviews/issues/62)

This project is not organized in the canonical ways a distributable piece of code should be in the standard Python universe. I recommend reviewing https://packaging.python.org/ and adding a setup.py.  Consider distributing commandline behaviors as `entry_points` console scripts.
Organizing and distributing your code in standard ways makes it more likely that other OSS users can take advantage of your brilliance.

**Comment by jkahn** [comment]
Whoops, I see that bug #1 might have already covered this.

**Comment by jkahn** [comment]
.... uh, no there's still plenty of work to do in matching the expected packaging.python.org format.  Distribution to PyPI, pip install behavior, etc etc.

**Comment by Dih5** [comment]
First of all, thank you for checking this. I'm afraid I only worried about pip in issue #1. Sorry, this was all new for me.

Checking https://packaging.python.org/distributing/  I have:
- Moved setup.py, setup.cfg and MANIFEST.in to the root. Also a small README.rst for PyPI, linking the .md at github.
- Cleaned pip install guide in readme.md.
- package as a module in a folder with an __ini__.py file
- console entry_point launching the GUI.

I think the structure is reasonably good now, but I would like to hear an expert opinion before closing the issue.

**Comment by Dih5** [comment]
I think the structure is now good enough according to these rules -at least to my rookie eye-, so I consider the issue closed.
If you find anything that can be improved, please do not hesitate to open a new one.
